messages:

  help: |
    &7Available commmands are: &f/%label%...
      &fcreate <region> &7to create a region.
      &fdelete <region> &7to delete a region.
      &fflag ... &7to set a flag.
      &fresponse ... &7to set a response.
      &fignore-y

  unknown-command: "&cCommand not found! Please use '/%label%'' to receive a list of all available commands."
  wrong-usage: "&cWronge usage! /%label% %usage%"
  missing-permission: "&cMissing permission %permission%!"

  create:
    success: "&aSuccessfully created the region %region%!"
    no-clipboard: "&cYou need to select an area first! Use a stone axe to select an area."

  delete:
    unknown-region: "&cThere's no region with that name!"
    success: "&aSuccessfully deleted the region %region%!"

  flag:
    specification:
      no-specification: "&cThis flag does not contain any specification values!"
      success: "&aSuccessfully set &e%flag% &afor &e%region% &aand the type &e%type% &ato &e%state%&a!"

  ignore-y:
    enabled: "&aRegion &e%region% &awill now ignore the Y-axis for its area."
    disabled: "&aRegion 6e%region% &awill now include the Y-axis for its area."

  info:
    unknown-region: "&cRegion not found!"
    no-region-here: "&cYou are not in a region!"
    message: |
      &7Region: &e%region%
      &7World: &e%world%
      &7Allowed flags: &a%allowed%
      &7Disallowed flags: &c%disallowed%

  list:
    message: "&7Regions: &e%regions%"
    empty: "&cNo regions!"

  response:
    success: "&aSet %response% for &e%flag% &aof region &e%region%&a."
    reset: "&aReset %response% response for &e%flag% &aof region &e%region%&a."

    sound:
      success: "&aSet sound for &e%flag% &aof region &e%region% &awith volume &e%volume% and pitch &e%pitch%&a."
      invalid-volume: "&cInvalid volume! (0.0 - 10.0)"
      invalid-pitch: "&cInvalid volume! (0.0 - 2.0)"
